name: steins_player
description: "Steins Player"
publish_to: 'none'
version: 0.3.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluent_ui: 
    git:
      url: https://github.com/bgli100/fluent_ui.git
      ref: master
  system_theme: ^3.2.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  file_selector: ^1.1.0
  window_manager: ^0.5.1
  http: ^1.6.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - res/global/
    - res/works/anon/
    - res/works/anon/segments/
    - res/works/soyo/
    - res/works/soyo/segments/
    - res/works/sakiko/
    - res/works/sakiko/segments/
    - res/works/tomori/
    - res/works/tomori/segments/
    - res/works/mutsumi/
    - res/works/mutsumi/segments/